name: Release Electron App

on:
  push:
    tags:
      - 'v*' # v1.0.10 등 태그가 달릴 때만 실행

jobs:
  build-app:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Check out Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 태그 정보 가져오기 필수

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Create Secrets
        shell: bash
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
        run: |
          echo "$ENV_FILE" > .env
          echo "$GCLOUD_KEY" > gcloud-key.json

      - name: Install Dependencies
        run: npm install

      # [중요] React를 먼저 빌드해서 'dist' 폴더를 만들어야 합니다!
      - name: Build React App
        run: npm run build:react

      # [배포 단계] dist 폴더가 생긴 후에 빌더를 실행합니다.
      - name: Build & Publish Electron
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        # npm run dist 대신, npx로 직접 실행해서 꼬임을 방지합니다.
        run: npx electron-builder --publish always